Revert "fix: add or remove nodedict entries when changing tree structure"
This reverts commit 1a29438ca650969864a5cc01226d630300bbe3f5.
The original commit caused several unit tests to fail, with this error:

FAILED tests/test_phylotreelib.py::Match_nodes::test_unmatchedroots - AttributeError: 'Nodestruct' object has no attribute '__dict__'. Did you mean: '__dir__'?
FAILED tests/test_phylotreelib_pytestversion.py::Test_is_bifurcation::test_trifurcations - KeyError: 0
FAILED tests/test_phylotreelib_pytestversion.py::Test_n_bipartitions::test_nonbifurcating_trees - KeyError: 6
FAILED tests/test_phylotreelib_pytestversion.py::TestSPR::test_spr_preserves_total_length_general_case - AttributeError: 'Nodestruct' object has no attribute '__dict__'. Did you mean: '__dir__'?

I think the issue is that in previous tests _nodedict was None and these test branches were not touched.
The reverted changes caused the nodedict to exist and since it now has __slots__ (so no __dict__)
these failed. Will refactor entire nodedict setup instead of going further down this path